apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: meureplicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
        labels:
            app: web
    spec:
        containers:
        - name: site
          image: thiagohauck/conversao-temperatura:v1
          ports:
          - containerPort: 8080
